# Generated by Django 3.2.18 on 2023-10-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_login_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_info',
        ),
    ]
