# Generated by Django 3.2.18 on 2023-10-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_delete_login_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post1', models.CharField(max_length=500)),
                ('post2', models.CharField(max_length=500)),
                ('post3', models.CharField(max_length=500)),
            ],
        ),
    ]
