# Generated by Django 3.2.18 on 2023-10-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_auto_20231031_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account_info',
        ),
    ]
