# Generated by Django 3.2.18 on 2023-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
