# Generated by Django 3.2.18 on 2023-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_trip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
