# Generated by Django 3.2.18 on 2023-11-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_alter_trip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
